# Generated by Django 3.0.5 on 2020-04-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200419_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('image', models.ImageField(blank=True, default='default.png', upload_to='profile_pics')),
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20, unique=True)),
                ('no_of_flights', models.IntegerField(blank=True, null=True)),
                ('head_office', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
