# Generated by Django 3.0.5 on 2020-04-21 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_flightinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinformation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Airline'),
        ),
    ]
