# Generated by Django 3.0.5 on 2020-04-21 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200421_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('image', models.ImageField(blank=True, default='default.png', upload_to='profile_pics')),
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20, unique=True)),
                ('no_of_buses', models.IntegerField(blank=True, null=True)),
                ('head_office', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('image', models.ImageField(blank=True, default='default.png', upload_to='profile_pics')),
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=20, unique=True)),
                ('no_of_rooms', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('hotel_address', models.CharField(max_length=50)),
                ('parking_available', models.BooleanField(choices=[('True', 'True'), ('False', 'False')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company_id', 'hotel_name')},
            },
        ),
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('room_type', models.CharField(max_length=20)),
                ('fare', models.IntegerField()),
                ('capacity', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=2)),
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('no_of_guests', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RoomInformation')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_journey', models.DateField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FlightInformation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='BusInformation',
            fields=[
                ('bus_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_point', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('no_of_haults', models.IntegerField(default=0)),
                ('fare', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_journey', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BusInformation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('wifi', models.BooleanField(choices=[('True', 'True'), ('False', 'False')])),
                ('ac', models.BooleanField(choices=[('True', 'True'), ('False', 'False')])),
                ('hot_water', models.BooleanField(choices=[('True', 'True'), ('False', 'False')])),
                ('breakfast', models.BooleanField(choices=[('True', 'True'), ('False', 'False')])),
                ('heater', models.BooleanField(choices=[('True', 'True'), ('False', 'False')])),
                ('tv', models.BooleanField(choices=[('True', 'True'), ('False', 'False')])),
                ('availability', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Hotel')),
            ],
            options={
                'unique_together': {('company', 'room_type')},
            },
        ),
    ]
