# Generated by Django 3.0.5 on 2020-04-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bus_busbooking_businformation_flightbooking_hotel_roombooking_roomfacilities_roominformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='no_of_seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Flightseats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remaining_seats', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FlightInformation')),
            ],
        ),
    ]
