# Generated by Django 3.0.5 on 2020-04-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInformation',
            fields=[
                ('flight_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_point', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('no_of_hautls', models.IntegerField(default=0)),
                ('fare', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Airline')),
            ],
        ),
    ]
