# Generated by Django 3.0.5 on 2020-04-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinformation',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flightinformation',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
