# Generated by Django 3.0.5 on 2020-04-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200420_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightInformation',
        ),
    ]
